# Verwende eine spezifische Java-Version
FROM openjdk:17-jdk-slim

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# The application's jar file
ARG JAR_FILE=*.jar

# Add the application's jar to the container
ADD ${JAR_FILE} intellimatch-0.0.1-SNAPSHOT.jar

# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/intellimatch-0.0.1-SNAPSHOT.jar"]
